package com.photoconnect.gateway.config;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.validation.annotation.Validated;

import java.util.List;

/**
 * Typed configuration for the JWT validation behaviour at the gateway edge.
 *
 * <p>Bound from {@code gateway.jwt.*}, which is served by config-service
 * (config-repo/api-gateway.properties) and has safe local-dev defaults in
 * api-gateway's own application.properties.</p>
 *
 * <p><b>publicKeyPath</b> — filesystem path to the RSA-2048 public key PEM
 * generated by {@code scripts/generate-keys.{sh,ps1}}. Both auth-service and
 * the gateway must use the <em>same</em> key; the private half never leaves
 * auth-service. Overridden in production via the
 * {@code AUTH_PUBLIC_KEY_PATH} environment variable.</p>
 *
 * <p><b>publicPaths</b> — Ant-style patterns that bypass JWT validation. Every
 * path not matched here is protected. Auth endpoints, actuator probes, and
 * Swagger routes all live in this list.</p>
 */
@Validated
@ConfigurationProperties(prefix = "gateway.jwt")
public record JwtGatewayProperties(

        /** Path to the PEM-encoded RSA public key used to verify token signatures. */
        @NotBlank String publicKeyPath,

        /** Must match the {@code iss} claim of every access token. */
        @NotBlank String issuer,

        /** Must match the {@code aud} claim of every access token. */
        @NotBlank String audience,

        /**
         * Ant patterns for paths that bypass JWT validation entirely.
         * Examples: {@code /api/v1/auth/**}, {@code /actuator/**}, {@code /swagger-ui/**}.
         */
        @NotNull List<String> publicPaths
) {}
