package com.photoconnect.photographer.service;

import com.photoconnect.photographer.domain.MediaType;
import com.photoconnect.photographer.domain.PhotographerProfile;
import com.photoconnect.photographer.domain.PortfolioItem;
import com.photoconnect.photographer.dto.FeedItemResponse;
import com.photoconnect.photographer.dto.PortfolioItemResponse;
import com.photoconnect.photographer.exception.InvalidPortfolioFileException;
import com.photoconnect.photographer.exception.PortfolioItemNotFoundException;
import com.photoconnect.photographer.exception.ProfileNotFoundException;
import com.photoconnect.photographer.repository.FeedRow;
import com.photoconnect.photographer.repository.PhotographerProfileRepository;
import com.photoconnect.photographer.repository.PortfolioItemRepository;
import org.springframework.data.domain.Limit;
import com.photoconnect.photographer.storage.StorageProperties;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.DeleteObjectRequest;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;

import java.io.IOException;
import java.util.List;
import java.util.UUID;

/**
 * Upload, list, and delete portfolio media for a photographer.
 *
 * <h2>Upload flow</h2>
 * <ol>
 *   <li>Validate the file (non-empty, MIME type matches the declared media type).</li>
 *   <li>Resolve the caller's profile by their auth userId (no profile → 404).</li>
 *   <li>Stream the bytes to S3/MinIO at {@code photographers/{profileId}/{itemId}.{ext}}.</li>
 *   <li>Save the metadata row with the resolved public URL.</li>
 * </ol>
 *
 * <p>If the DB insert fails after the S3 PUT succeeded we'd leak an object —
 * a real consistency concern, but for an MVP the rare race is acceptable.
 * Phase 2 fix: use a "pending → committed" status field and a sweeper job.</p>
 */
@Slf4j
@Service
@Transactional
@RequiredArgsConstructor
public class PortfolioService {

    private final PortfolioItemRepository portfolioRepo;
    private final PhotographerProfileRepository profileRepo;
    private final S3Client s3;
    private final StorageProperties storage;

    /** Upload a new sample asset for the calling photographer. */
    public PortfolioItemResponse upload(UUID userId, MultipartFile file,
                                         MediaType mediaType, String category) {
        if (file == null || file.isEmpty()) {
            throw new InvalidPortfolioFileException("Uploaded file is empty");
        }
        String mime = file.getContentType();
        if (mime == null || mime.isBlank()) {
            throw new InvalidPortfolioFileException("Missing Content-Type on uploaded file");
        }
        validateMimeForType(mediaType, mime);

        PhotographerProfile profile = profileRepo.findByUserId(userId)
                .orElseThrow(() -> new ProfileNotFoundException(userId));

        // Storage key uses its own UUID so we can upload BEFORE the DB insert.
        // We deliberately do NOT pre-set the entity's @Id field — Spring Data's
        // default isNew() check sees a non-null ID and calls merge() instead of
        // persist(), which then fails with StaleObjectStateException because no
        // matching row exists yet. Letting JPA generate the entity ID at persist
        // time keeps save() on the INSERT path.
        UUID storageId = UUID.randomUUID();
        String key = "photographers/" + profile.getId() + "/" + storageId + extensionFor(mime);

        // ── Upload bytes to S3/MinIO ──────────────────────────────────────────
        try {
            s3.putObject(
                    PutObjectRequest.builder()
                            .bucket(storage.bucket())
                            .key(key)
                            .contentType(mime)
                            .contentLength(file.getSize())
                            .build(),
                    RequestBody.fromInputStream(file.getInputStream(), file.getSize()));
        } catch (IOException e) {
            throw new InvalidPortfolioFileException("Could not read upload stream: " + e.getMessage());
        }

        // ── Save metadata row (entity ID generated by JPA on persist) ─────────
        PortfolioItem item = new PortfolioItem();
        item.setPhotographerProfileId(profile.getId());
        item.setMediaType(mediaType);
        item.setCategory(category.trim().toLowerCase());
        item.setMimeType(mime);
        item.setSizeBytes(file.getSize());
        item.setStorageKey(key);
        item.setPublicUrl(buildPublicUrl(key));
        item.setDisplayOrder(0);
        PortfolioItem saved = portfolioRepo.save(item);

        log.info("Uploaded portfolio item {} ({} bytes, {}) for profile {}",
                saved.getId(), saved.getSizeBytes(), saved.getMimeType(), profile.getId());
        return toResponse(saved);
    }

    /** List a specific photographer's portfolio — used by the public detail page. */
    @Transactional(readOnly = true)
    public List<PortfolioItemResponse> listForProfile(UUID profileId, MediaType mediaTypeFilter,
                                                       String categoryFilter) {
        List<PortfolioItem> items;
        if (mediaTypeFilter != null) {
            items = portfolioRepo
                    .findByPhotographerProfileIdAndMediaTypeOrderByDisplayOrderAscUploadedAtAsc(
                            profileId, mediaTypeFilter);
        } else if (categoryFilter != null && !categoryFilter.isBlank()) {
            items = portfolioRepo
                    .findByPhotographerProfileIdAndCategoryOrderByDisplayOrderAscUploadedAtAsc(
                            profileId, categoryFilter.trim().toLowerCase());
        } else {
            items = portfolioRepo
                    .findByPhotographerProfileIdOrderByDisplayOrderAscUploadedAtAsc(profileId);
        }
        return items.stream().map(PortfolioService::toResponse).toList();
    }

    /**
     * Marketplace feed — newest portfolio items across all available photographers.
     *
     * <p>Each item carries an embedded {@code photographer} snippet so the SPA
     * can render the tile + name overlay + link in a single response.
     * Sorted by upload time, newest first.</p>
     */
    @Transactional(readOnly = true)
    public List<FeedItemResponse> listFeed(int limit) {
        int safe = Math.max(1, Math.min(limit, 200));
        return portfolioRepo.findFeed(Limit.of(safe)).stream()
                .map(PortfolioService::toFeedResponse)
                .toList();
    }

    /** List the calling photographer's own portfolio (resolved from userId, not profile PK). */
    @Transactional(readOnly = true)
    public List<PortfolioItemResponse> listMine(UUID userId) {
        PhotographerProfile profile = profileRepo.findByUserId(userId)
                .orElseThrow(() -> new ProfileNotFoundException(userId));
        return listForProfile(profile.getId(), null, null);
    }

    /**
     * Delete a portfolio item owned by the calling photographer.
     * Best-effort: we delete the S3 object first, then the row. If the S3 call
     * succeeds but the row delete fails (rare), the DB still has a row pointing
     * at a missing object — listing would show a broken thumbnail. A periodic
     * reconciliation job (Phase 2) would catch that.
     */
    public void delete(UUID userId, UUID itemId) {
        PortfolioItem item = portfolioRepo.findById(itemId)
                .orElseThrow(() -> new PortfolioItemNotFoundException(itemId));

        PhotographerProfile profile = profileRepo.findByUserId(userId)
                .orElseThrow(() -> new ProfileNotFoundException(userId));

        // Ownership check — service layer enforces, defence-in-depth alongside @PreAuthorize.
        if (!item.getPhotographerProfileId().equals(profile.getId())) {
            throw new AccessDeniedException("You can only delete your own portfolio items");
        }

        s3.deleteObject(DeleteObjectRequest.builder()
                .bucket(storage.bucket())
                .key(item.getStorageKey())
                .build());
        portfolioRepo.delete(item);
        log.info("Deleted portfolio item {} for profile {}", itemId, profile.getId());
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /** Build the direct-fetch URL the SPA will use in <img>/<video>. */
    private String buildPublicUrl(String key) {
        String prefix = storage.publicUrlPrefix();
        if (prefix.endsWith("/")) prefix = prefix.substring(0, prefix.length() - 1);
        return prefix + "/" + storage.bucket() + "/" + key;
    }

    private static void validateMimeForType(MediaType type, String mime) {
        boolean ok = switch (type) {
            case IMAGE -> mime.startsWith("image/");
            case VIDEO, REEL -> mime.startsWith("video/");
        };
        if (!ok) {
            throw new InvalidPortfolioFileException(
                    "MIME type " + mime + " does not match declared media type " + type);
        }
    }

    private static String extensionFor(String mime) {
        // Cheap MIME → extension map. Anything not on this list keeps no extension —
        // the Content-Type stored on the object is what actually matters for playback.
        return switch (mime) {
            case "image/jpeg" -> ".jpg";
            case "image/png"  -> ".png";
            case "image/webp" -> ".webp";
            case "image/gif"  -> ".gif";
            case "video/mp4"  -> ".mp4";
            case "video/webm" -> ".webm";
            case "video/quicktime" -> ".mov";
            default -> "";
        };
    }

    private static FeedItemResponse toFeedResponse(FeedRow r) {
        return new FeedItemResponse(
                r.itemId(),
                r.mediaType(),
                r.category(),
                r.mimeType(),
                r.publicUrl(),
                r.uploadedAt(),
                new FeedItemResponse.PhotographerSnippet(
                        r.photographerProfileId(),
                        r.photographerName(),
                        r.photographerLocation()));
    }

    private static PortfolioItemResponse toResponse(PortfolioItem i) {
        return new PortfolioItemResponse(
                i.getId(),
                i.getPhotographerProfileId(),
                i.getMediaType(),
                i.getCategory(),
                i.getMimeType(),
                i.getSizeBytes(),
                i.getPublicUrl(),
                i.getDisplayOrder(),
                i.getUploadedAt());
    }
}
